build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                environment:
                    php:
                        pecl_extensions:
                            - redis
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - phpcs-run --standard=phpcs.xml
                    - vendor/bin/security-checker security:check

        coverage:
            tests:
                override:
                    - command: vendor/bin/phpunit
                      coverage:
                        file: docs/coverage.xml
                        format: clover

checks:
    php: true

filter:
    excluded_paths:
        - tests/*
